#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh

restore0Dir

runApplication snappyHexMesh -overwrite

runApplication $(getApplication)

foamLog log.$(getApplication)

python plotResiduals.py

#------------------------------------------------------------------------------
